module.exports = [
  {
    picture: './dist/img/people.jpg',
    verified: 'Jeden',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Dwa',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Trzy',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Cztery',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Pięć',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Sześć',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Siedem',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Osiem',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  },
  {
    picture: './dist/img/people.jpg',
    verified: 'Dziewięć',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.',
    rating: '2',
    title: 'programista',
    industry: 'IT - Rozwój oprogramowania',
    destination: 'Zdalnie',
    salary: '12000',
    availability: 'za miesiąc',
    languages: 'Angielski, Polski',
    price: '500zł',
  }
]
